# Generated by Django 6.0.7 on 2026-07-23 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0009_coupon'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='featured',
            field=models.BooleanField(default=False),
        ),
    ]
