# Generated by Django 6.0.7 on 2026-07-23 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0010_order_featured'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='featured',
        ),
        migrations.AddField(
            model_name='product',
            name='featured',
            field=models.BooleanField(default=False),
        ),
    ]
